version: '3.7'

services:
  bot:
    build: .
    image: in-house-queue
    env_file:
      - .env
    volumes:
      - inhouse-db:/app/db

  backup:
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_PRUNING_PREFIX: backup-
      BACKUP_CRON_EXPRESSION: "* * * * *"
      BACKUP_RETENTION_DAYS: "7"
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_PATH: ${AWS_S3_PATH}
    volumes:
      - inhouse-db:/backup/inhouse-db-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  inhouse-db:
