name: Update Bot V2 - Live
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
  pull-repo:
    name: pull latest repo
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ env.REPO_NAME }}
          git pull
  restart-bot:
    name: restart bot
    needs: pull-repo
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.ROOT_USERNAME }}
        password: ${{ secrets.ROOT_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: sudo systemctl start ${{ env.REPO_NAME }}-watcher.service
